### ISSUE TITLE
README documentation is out-of-date

### ISSUE THREAD

**Issue by duncanmmacleod** [lscsoft/pcat#2]
Now that #1 has been merged, the README file is out-of-date and needs to be updated.

Specifically any installation instructions should reference just installing from pip

``` bash
pip install git+https://github.com/lscsoft/pcat.git
```

or for a local install

``` bash
git clone https://github.com/lscsoft/pcat
cd pcat
pip install .
```

and the Lab-LDG GWpy sourcing should be updated to use the `activate` script:

``` bash
. ~detchar/opt/gwpysoft/bin/activate
```

Also, the main executable has been renamed from `PCAT.py` to just `pcat`, so references to

``` bash
python PCAT.py ...
```

should be changed to simply (assuming the executable is already on the `PATH`)

``` bash
pcat ...
```

**Comment by cavaglia** [comment]
It should be OK now
